### ISSUE TITLE
Rita

### ISSUE THREAD

**Issue by RitaBorowska** [Javagda40z/Rita-Borowska#1]
Hey Mateusz @implssv , wysłałam zadnia z tablic, czasu i dat.... mógłbyś zerknąć ?

**Comment by implssv** [comment]
Jeżeli chodzi o zadanie z tablic to możesz skorzystać z pętli :).  Jeżeli chodzi o zadanie 6 to jest tam informacja o pomnożeniu elementów tablicy a nie sum tablic. Zadanie 8 można było zrobić bez kopiowania tablic po prostu iterując po dwóch tablicach.

Co do dat:

`DateTimeFormatter.ofPattern(" 'at' HH:mm:ss E yyyy-MM-dd");`

W jakim celu jest tutaj 'at'?

W zadaniu 4 możesz skorzystać z tego : https://beginnersbook.com/2017/10/java-8-calculate-days-between-two-dates/ 

Spróbuj jeszcze z rokiem przestępnym :)
